<div class="message">
    <h1>Сообщения из потустороннего мира.</h1>
    <p>Многие воспринимают каптчу как просто проверку на то, человек совершает
    действия или бот. На многих каптчах информация кажется совершенно не имеющией
    смысла, но если приглядеться…</p>
    <p>Если приглядеться, она оказывается полна смысла и зачастую особой мудрости.
    Как будто некто «с той стороны» хочет что-то сказать, но глупые слепцы даже
    не пытаются понять.</p>
    <p>Числа — это на самом деле не просто числа. Буквы — это не просто буквы.
    Слова складываются в послания. Это <a href="/about/" title="Кто такой Инглип">тёмный лорд Инглип</a> изъявляет свою волю:</p>
<script type="text/ecmascript">/*<![CDATA[*/
    function reloadClaim()
    {
        claim = document.getElementById('claim-image');
        if (claim) {
            claim.src = '/images/claim.png?u=' + Math.random();
        }
    }
/*]]>*/</script>
    <div id="claim-box">
        <img src="/images/claim.png?u=<?php echo microtime(1); ?>" width="300" height="57" id="claim-image" alt="Приказ лорда Инглипа" />
        <div id="claim-reloader" onclick="reloadClaim()" title="Получить новое указание">&nbsp;</div>
    </div>
    <p class="notice">Для получения нового приказа обнови страницу. Или нажми на стрелочку на кнопке.</p>
    <dl class="codes">
        <dt><label for="code-url">URL картинки</label></dt>
        <dd><input id="code-url" readonly="readonly" value="http://inglip.ru/images/captcha.png" onclick="this.select();" /></dd>
        <dt><label for="code-big">Для вставки в блог</label></dt>
        <dd><textarea cols="20" rows="3" id="code-big" onclick="this.select();"><?php
        echo htmlspecialchars('<a href="http://inglip.ru/" title="Inglip summoned" rel="external follow"><img src="http://inglip.ru/images/captcha.png" width="312" height="123" alt="Приказ лорда Инглипа" style="border:none" border="0" /></a>');
        ?></textarea></dd>
    </dl>
</div>
<div class="message"><div class="social-block">
    <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Finglip.ru&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe>
    <div id="vk_like"></div>
    <script type="text/javascript">
    VK.Widgets.Like("vk_like", {type: "button", verb: 1});
    </script>
    <p><a href="http://twitter.com/#!/inglip_ru">Приказы в Твиттере</a></p>
</div></div>
