default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inglip3
  #username: inglip_ru
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: inglip3_test

production:
  <<: *default
  database: inglip3
  username: inglip
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
