<?php if (!$this->showForm): ?>
<p><a href="/manage/">К списку всего</a></p>
<form action="/manage/addsubject/" method="post" class="message">
    <dl>
        <dt><label for="gender">Род</label></dt>
        <dd>
            <select name="gender" id="gender">
                <option value="0">Мужской</option>
                <option value="1">Женский</option>
                <option value="2">Средний</option>
            </select>
        </dd>
        <dd class="notice">Во множественном числе слова не пролезут :(</dd>
        <dd>
            <input type="checkbox" id="adjective" name="is_descriptive" class="fl" />
            <label for="adjective">Может быть прилагательным</label>
        </dd>
        <dt><label for="words">Слова через запятую</label></dt>
        <dd><textarea cols="40" rows="7" id="words" name="words"></textarea></dd>
        <dt><label for="submit">Подчиниться!</label></dt>
        <dd><button type="submit" id="submit"><?php echo \models\Claim::get(); ?></button></dd>
    </dl>
</form>
<p>Добавлено: <?php echo $this->added; ?></p>
<?php endif; ?>