<?php if ($this->showForm): ?>
<form action="/manage/auth" method="post" class="message">
    <dl>
        <dt><label for="login">Login</label></dt>
        <dd><input type="text" name="login" id="login" size="20" /></dd>
        <dt><label for="password">Password</label></dt>
        <dd><input type="password" name="password" id="password" /></dd>
        <dt><label for="submit">Submit</label></dt>
        <dd><button type="submit" id="submit"><?php echo \models\Claim::get(); ?></button></dd>
    </dl>
</form>
<?php else: ?>
<p><a href="/manage/">Oh, hi!</a></p>
<?php endif; ?>